[workspace]

members = [
  "crates/posts",
  "crates/users",
  "crates/communities",
  "crates/photos",
  "crates/photo_files",
  "crates/photo_files_2",
  "crates/api",
  "crates/front",

  "crates/yew",
]
