[workspace]

members = [
  "crates/posts",
  "crates/users",
  "crates/communities",
  "crates/photos",
  #"crates/chats",
  "crates/photo_files",
  "crates/photo_files_2",
  "crates/api",
  "crates/front",
]
